<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class PerencanaansTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('perencanaans')->delete();
        
        \DB::table('perencanaans')->insert(array (
            0 => 
            array (
                'id' => 31,
                'user_id' => 31,
                'provinsi' => 'Sumatera Utara',
                'kab_kota' => 'Kabupaten Simalungun',
                'jenis_mp' => 'Ikan Mas',
                'jenis_hpik' => 'SVCV, KHV, CEV, Aeromonas salmonicida, Yersinia ruckeri, Aphanomyces invadans',
                'kemampuan_uji_upt' => 'KHV, Aeromonas salmonicida',
                'metode_pengujian' => 'PCR Konvensional dan Bakteri Konvensional',
                'lab_uji' => 'BBKHIT Sumatera Utara',
                'target_uji' => 6,
                'tw1' => 0,
                'tw2' => 2,
                'tw3' => 0,
                'tw4' => 2,
                'total_pengujian' => 4,
                'rencana_lokasi' => '- Pokdakan di Desa Nagori Kec. Gunung Malela
- BBI Rambung Merah Kec. Siantar
- Pokdakan di Desa Silau Malaha Kec. Siantar',
                'rencana_jumlah_sampel' => 12,
                'rencana_metode_sampling' => 'acak',
                'status' => 'approved',
                'alasan_penolakan' => NULL,
                'created_at' => '2026-07-08 06:13:00',
                'updated_at' => '2026-07-08 06:13:00',
            ),
            1 => 
            array (
                'id' => 32,
                'user_id' => 31,
                'provinsi' => 'Sumatera Utara',
                'kab_kota' => 'Kabupaten Simalungun',
                'jenis_mp' => 'Ikan Nila',
                'jenis_hpik' => 'VNN, TiLV, E. ictaluri, A. salmonicida, S. agalactiae, S. iniae, Yersinia ruckeri, A. invadans',
                'kemampuan_uji_upt' => 'TiLV, Aeromonas salmonicida, Streptococcus iniae',
                'metode_pengujian' => 'PCR Konvensional dan Bakteri Konvensional',
                'lab_uji' => 'BBKHIT Sumatera Utara',
                'target_uji' => 8,
                'tw1' => 0,
                'tw2' => 3,
                'tw3' => 0,
                'tw4' => 3,
                'total_pengujian' => 6,
                'rencana_lokasi' => '- Pokdakan di Desa Nagori Kec. Gunung Malela
- BBI Rambung Merah Kec. Siantar
- Pokdakan di Desa Silau Malaha Kec. Siantar',
                'rencana_jumlah_sampel' => 18,
                'rencana_metode_sampling' => 'acak',
                'status' => 'approved',
                'alasan_penolakan' => NULL,
                'created_at' => '2026-07-08 06:13:00',
                'updated_at' => '2026-07-08 06:13:00',
            ),
            2 => 
            array (
                'id' => 33,
                'user_id' => 31,
                'provinsi' => 'Sumatera Utara',
                'kab_kota' => 'Kabupaten Deli Serdang',
                'jenis_mp' => 'Ikan Mas',
                'jenis_hpik' => 'SVCV, KHV, CEV, A. salmonicida, Yersinia ruckeri, A. invadans',
                'kemampuan_uji_upt' => 'KHV, Aeromonas salmonicida',
                'metode_pengujian' => 'PCR Konvensional dan Bakteri Konvensional',
                'lab_uji' => 'BBKHIT Sumatera Utara',
                'target_uji' => 6,
                'tw1' => 0,
                'tw2' => 2,
                'tw3' => 0,
                'tw4' => 2,
                'total_pengujian' => 4,
                'rencana_lokasi' => '- Pokdakan di Desa Lengau Seprang Kec. Tj. Morawa',
                'rencana_jumlah_sampel' => 12,
                'rencana_metode_sampling' => 'acak',
                'status' => 'approved',
                'alasan_penolakan' => NULL,
                'created_at' => '2026-07-08 06:13:00',
                'updated_at' => '2026-07-08 06:13:00',
            ),
            3 => 
            array (
                'id' => 34,
                'user_id' => 31,
                'provinsi' => 'Sumatera Utara',
                'kab_kota' => 'Kabupaten Deli Serdang',
                'jenis_mp' => 'Ikan Nila',
                'jenis_hpik' => 'VNN, TiLV, E. ictaluri, A. salmonicida, S. agalactiae, S. iniae, Yersinia ruckeri, A. invadans',
                'kemampuan_uji_upt' => 'TiLV, Aeromonas salmonicida, Streptococcus iniae',
                'metode_pengujian' => 'PCR Konvensional dan Bakteri Konvensional',
                'lab_uji' => 'BBKHIT Sumatera Utara',
                'target_uji' => 8,
                'tw1' => 0,
                'tw2' => 3,
                'tw3' => 0,
                'tw4' => 3,
                'total_pengujian' => 6,
                'rencana_lokasi' => '- Pokdakan di Desa Lengau Seprang Kec. Tj. Morawa
- Pokdakan di Desa Tanjung Mulia Kec. Tj. Morawa',
                'rencana_jumlah_sampel' => 18,
                'rencana_metode_sampling' => 'acak',
                'status' => 'approved',
                'alasan_penolakan' => NULL,
                'created_at' => '2026-07-08 06:13:00',
                'updated_at' => '2026-07-08 06:13:00',
            ),
            4 => 
            array (
                'id' => 35,
                'user_id' => 31,
                'provinsi' => 'Sumatera Utara',
                'kab_kota' => 'Kabupaten Deli Serdang',
                'jenis_mp' => 'Udang Vannamei',
                'jenis_hpik' => 'WSSV, TSV, AHPND, IMNV, IHHNV, YHV, CMNV, EHP, NHP, DIV-1',
                'kemampuan_uji_upt' => 'WSSV, TSV, AHPND, IMNV, IHHNV, YHV, CMNV, EHP, NHP, DIV-1',
                'metode_pengujian' => 'PCR Konvensional',
                'lab_uji' => 'BBKHIT Sumatera Utara',
                'target_uji' => 10,
                'tw1' => 0,
                'tw2' => 10,
                'tw3' => 0,
                'tw4' => 10,
                'total_pengujian' => 20,
                'rencana_lokasi' => '- Pokdakan di Desa Percut Kec. Percut Sei Tuan',
                'rencana_jumlah_sampel' => 60,
                'rencana_metode_sampling' => 'acak',
                'status' => 'approved',
                'alasan_penolakan' => NULL,
                'created_at' => '2026-07-08 06:13:00',
                'updated_at' => '2026-07-08 06:13:00',
            ),
            5 => 
            array (
                'id' => 36,
                'user_id' => 31,
                'provinsi' => 'Sumatera Utara',
                'kab_kota' => 'Kabupaten Batu Bara',
                'jenis_mp' => 'Ikan Kerapu Lumpur',
                'jenis_hpik' => 'RSIV, ISKNV, GIV, VNN',
                'kemampuan_uji_upt' => 'RSIV, VNN',
                'metode_pengujian' => 'PCR Konvensional',
                'lab_uji' => 'BBKHIT Sumatera Utara',
                'target_uji' => 4,
                'tw1' => 0,
                'tw2' => 2,
                'tw3' => 0,
                'tw4' => 2,
                'total_pengujian' => 4,
                'rencana_lokasi' => '- Pokdakan di Desa Mesjid Lama Kec. Talawi',
                'rencana_jumlah_sampel' => 12,
                'rencana_metode_sampling' => 'acak',
                'status' => 'approved',
                'alasan_penolakan' => NULL,
                'created_at' => '2026-07-08 06:13:00',
                'updated_at' => '2026-07-08 06:13:00',
            ),
            6 => 
            array (
                'id' => 37,
                'user_id' => 31,
                'provinsi' => 'Sumatera Utara',
                'kab_kota' => 'Kabupaten Batu Bara',
                'jenis_mp' => 'Udang Vannamei',
                'jenis_hpik' => 'WSSV, TSV, AHPND, IMNV, IHHNV, YHV, CMNV, EHP, NHP, DIV-1',
                'kemampuan_uji_upt' => 'WSSV, TSV, AHPND, IMNV, IHHNV, YHV, CMNV, EHP, NHP, DIV-1',
                'metode_pengujian' => 'PCR Konvensional',
                'lab_uji' => 'BBKHIT Sumatera Utara',
                'target_uji' => 10,
                'tw1' => 0,
                'tw2' => 10,
                'tw3' => 0,
                'tw4' => 10,
                'total_pengujian' => 20,
                'rencana_lokasi' => '- Pokdakan di Lalang Kec. Medang Deras
- Pokdakan di Desa Nenas Siam Kec. Medang Deras',
                'rencana_jumlah_sampel' => 60,
                'rencana_metode_sampling' => 'acak',
                'status' => 'approved',
                'alasan_penolakan' => NULL,
                'created_at' => '2026-07-08 06:13:00',
                'updated_at' => '2026-07-08 06:13:00',
            ),
            7 => 
            array (
                'id' => 38,
                'user_id' => 31,
                'provinsi' => 'Sumatera Utara',
                'kab_kota' => 'Kabupaten Langkat',
                'jenis_mp' => 'Kepiting',
                'jenis_hpik' => 'WSSV',
                'kemampuan_uji_upt' => 'WSSV',
                'metode_pengujian' => 'PCR Konvensional',
                'lab_uji' => 'BBKHIT Sumatera Utara',
                'target_uji' => 1,
                'tw1' => 0,
                'tw2' => 1,
                'tw3' => 0,
                'tw4' => 1,
                'total_pengujian' => 2,
                'rencana_lokasi' => '- Pokdakan Kelurahan Alur Dua Baru Kec. Sei Lepan',
                'rencana_jumlah_sampel' => 6,
                'rencana_metode_sampling' => 'acak',
                'status' => 'approved',
                'alasan_penolakan' => NULL,
                'created_at' => '2026-07-08 06:13:00',
                'updated_at' => '2026-07-08 06:13:00',
            ),
            8 => 
            array (
                'id' => 39,
                'user_id' => 31,
                'provinsi' => 'Sumatera Utara',
                'kab_kota' => 'Kabupaten Langkat',
                'jenis_mp' => 'Udang Vannamei',
                'jenis_hpik' => 'WSSV, TSV, AHPND, IMNV, IHHNV, YHV, CMNV, EHP, NHP, DIV-1',
                'kemampuan_uji_upt' => 'WSSV, TSV, AHPND, IMNV, IHHNV, YHV, CMNV, EHP, NHP, DIV-1',
                'metode_pengujian' => 'PCR Konvensional',
                'lab_uji' => 'BBKHIT Sumatera Utara',
                'target_uji' => 10,
                'tw1' => 0,
                'tw2' => 10,
                'tw3' => 0,
                'tw4' => 10,
                'total_pengujian' => 20,
                'rencana_lokasi' => '- Kampung perikanan budidaya di Desa Alur Dua Baru Kelurahan Brandan Barat Kec. Sei Lepan',
                'rencana_jumlah_sampel' => 60,
                'rencana_metode_sampling' => 'acak',
                'status' => 'approved',
                'alasan_penolakan' => NULL,
                'created_at' => '2026-07-08 06:13:00',
                'updated_at' => '2026-07-08 06:13:00',
            ),
            9 => 
            array (
                'id' => 40,
                'user_id' => 31,
                'provinsi' => 'Sumatera Utara',
                'kab_kota' => 'Kota Tebing Tinggi',
                'jenis_mp' => 'Ikan Mas',
                'jenis_hpik' => 'SVCV, KHV, CEV, A. salmonicida, Yersinia ruckeri, A. invadans',
                'kemampuan_uji_upt' => 'KHV, Aeromonas salmonicida',
                'metode_pengujian' => 'PCR Konvensional dan Bakteri Konvensional',
                'lab_uji' => 'BBKHIT Sumatera Utara',
                'target_uji' => 6,
                'tw1' => 0,
                'tw2' => 2,
                'tw3' => 0,
                'tw4' => 2,
                'total_pengujian' => 4,
                'rencana_lokasi' => '- BBI Pinang Mancung Kec. Bajenis
- Pokdakan di Kec. Rambutan
- Pokdakan di Kec. Tebing Tinggi Kota',
                'rencana_jumlah_sampel' => 12,
                'rencana_metode_sampling' => 'acak',
                'status' => 'approved',
                'alasan_penolakan' => NULL,
                'created_at' => '2026-07-08 06:13:00',
                'updated_at' => '2026-07-08 06:13:00',
            ),
            10 => 
            array (
                'id' => 41,
                'user_id' => 31,
                'provinsi' => 'Sumatera Utara',
                'kab_kota' => 'Kota Tebing Tinggi',
                'jenis_mp' => 'Ikan Nila',
                'jenis_hpik' => 'VNN, TiLV, E. ictaluri, A. salmonicida, S. agalactiae, Y. ruckeri, A. invadans',
                'kemampuan_uji_upt' => 'TiLV, Aeromonas salmonicida, Streptococcus iniae',
                'metode_pengujian' => 'PCR Konvensional dan Bakteri Konvensional',
                'lab_uji' => 'BBKHIT Sumatera Utara',
                'target_uji' => 8,
                'tw1' => 0,
                'tw2' => 3,
                'tw3' => 0,
                'tw4' => 3,
                'total_pengujian' => 6,
                'rencana_lokasi' => '- BBI Pinang Mancung Kec. Bajenis
- Pokdakan di Kec. Rambutan
- Pokdakan di Kec. Tebing Tinggi Kota',
                'rencana_jumlah_sampel' => 18,
                'rencana_metode_sampling' => 'acak',
                'status' => 'approved',
                'alasan_penolakan' => NULL,
                'created_at' => '2026-07-08 06:13:00',
                'updated_at' => '2026-07-08 06:13:00',
            ),
            11 => 
            array (
                'id' => 42,
                'user_id' => 31,
                'provinsi' => 'Sumatera Utara',
                'kab_kota' => 'Kabupaten Toba',
                'jenis_mp' => 'Ikan Mas',
                'jenis_hpik' => 'SVCV, KHV, CEV, A. salmonicida, Yersinia ruckeri, Aphanomyces invadans',
                'kemampuan_uji_upt' => 'KHV, Aeromonas salmonicida',
                'metode_pengujian' => 'PCR Konvensional dan Bakteri Konvensional',
            'lab_uji' => 'BBKHIT Sumatera Utara, BKHIT Banten (SVCV)',
                'target_uji' => 6,
                'tw1' => 0,
                'tw2' => 2,
                'tw3' => 0,
                'tw4' => 2,
                'total_pengujian' => 4,
                'rencana_lokasi' => '- Pokdakan di Kel. Patane III Kec. Porsea
- Pokdakan di Parsaoran Kec. Ajibata
- Pokdakan di Desa Pardamean, Kec. Ajibata',
                'rencana_jumlah_sampel' => 12,
                'rencana_metode_sampling' => 'acak',
                'status' => 'approved',
                'alasan_penolakan' => NULL,
                'created_at' => '2026-07-08 06:13:00',
                'updated_at' => '2026-07-08 06:13:00',
            ),
            12 => 
            array (
                'id' => 43,
                'user_id' => 31,
                'provinsi' => 'Sumatera Utara',
                'kab_kota' => 'Kabupaten Toba',
                'jenis_mp' => 'Ikan Nila',
                'jenis_hpik' => 'VNN, TiLV, E. ictaluri, A. salmonicida, S. agalactiae, Yersinia ruckeri, A. invadans',
                'kemampuan_uji_upt' => 'TiLV, Streptococcus iniae, Aeromonas salmonicida',
                'metode_pengujian' => 'PCR Konvensional dan Bakteri Konvensional',
                'lab_uji' => 'BBKHIT Sumatera Utara',
                'target_uji' => 8,
                'tw1' => 0,
                'tw2' => 3,
                'tw3' => 0,
                'tw4' => 3,
                'total_pengujian' => 6,
                'rencana_lokasi' => '- Pokdakan di Kel. Patane III Kec. Porsea
- Pokdakan di Parsaoran Kec. Ajibata',
                'rencana_jumlah_sampel' => 18,
                'rencana_metode_sampling' => 'acak',
                'status' => 'approved',
                'alasan_penolakan' => NULL,
                'created_at' => '2026-07-08 06:13:00',
                'updated_at' => '2026-07-08 06:13:00',
            ),
            13 => 
            array (
                'id' => 44,
                'user_id' => 35,
                'provinsi' => 'Aceh',
                'kab_kota' => 'Bireuen',
                'jenis_mp' => 'Udang Vannamei',
                'jenis_hpik' => 'WSSV, TSV, AHPND, IMNV, IHHNV, YHV, CMNV, EHP, NHP, DIV-1',
                'kemampuan_uji_upt' => 'WSSV, TSV, AHPND, IMNV, IHHNV, YHV, EHP',
                'metode_pengujian' => 'PCR Konvensional',
                'lab_uji' => 'BKHIT Aceh',
                'target_uji' => 7,
                'tw1' => 0,
                'tw2' => 7,
                'tw3' => 7,
                'tw4' => 0,
                'total_pengujian' => 14,
                'rencana_lokasi' => 'Tambak Bireuen',
                'rencana_jumlah_sampel' => 8,
                'rencana_metode_sampling' => 'Acak',
                'status' => 'approved',
                'alasan_penolakan' => NULL,
                'created_at' => '2026-07-08 06:19:39',
                'updated_at' => '2026-07-08 06:19:39',
            ),
            14 => 
            array (
                'id' => 45,
                'user_id' => 35,
                'provinsi' => 'Aceh',
                'kab_kota' => 'Bireuen',
                'jenis_mp' => 'Kerapu',
                'jenis_hpik' => 'RSIVD, VNN',
                'kemampuan_uji_upt' => 'RSIVD, VNN',
                'metode_pengujian' => 'PCR Konvensional',
                'lab_uji' => 'BKHIT Aceh',
                'target_uji' => 2,
                'tw1' => 0,
                'tw2' => 2,
                'tw3' => 2,
                'tw4' => 0,
                'total_pengujian' => 4,
                'rencana_lokasi' => 'Tambak Bireuen',
                'rencana_jumlah_sampel' => 2,
                'rencana_metode_sampling' => 'Acak',
                'status' => 'approved',
                'alasan_penolakan' => NULL,
                'created_at' => '2026-07-08 06:19:39',
                'updated_at' => '2026-07-08 06:19:39',
            ),
            15 => 
            array (
                'id' => 46,
                'user_id' => 35,
                'provinsi' => 'Aceh',
                'kab_kota' => 'Lhokseumawe',
                'jenis_mp' => 'Udang Vannamei',
                'jenis_hpik' => 'WSSV, TSV, AHPND, IMNV, IHHNV, YHV, CMNV, EHP, NHP, DIV-1',
                'kemampuan_uji_upt' => 'WSSV, TSV, AHPND, IMNV, IHHNV, YHV, EHP',
                'metode_pengujian' => 'PCR Konvensional',
                'lab_uji' => 'BKHIT Aceh',
                'target_uji' => 7,
                'tw1' => 0,
                'tw2' => 7,
                'tw3' => 7,
                'tw4' => 0,
                'total_pengujian' => 14,
                'rencana_lokasi' => 'Tambak Lhokseumawe',
                'rencana_jumlah_sampel' => 8,
                'rencana_metode_sampling' => 'Acak',
                'status' => 'approved',
                'alasan_penolakan' => NULL,
                'created_at' => '2026-07-08 06:19:39',
                'updated_at' => '2026-07-08 06:19:39',
            ),
            16 => 
            array (
                'id' => 47,
                'user_id' => 35,
                'provinsi' => 'Aceh',
                'kab_kota' => 'Lhokseumawe',
                'jenis_mp' => 'Kerapu',
                'jenis_hpik' => 'RSIVD, VNN',
                'kemampuan_uji_upt' => 'RSIVD, VNN',
                'metode_pengujian' => 'PCR Konvensional',
                'lab_uji' => 'BKHIT Aceh',
                'target_uji' => 2,
                'tw1' => 0,
                'tw2' => 2,
                'tw3' => 2,
                'tw4' => 0,
                'total_pengujian' => 4,
                'rencana_lokasi' => 'Tambak Lhokseumawe',
                'rencana_jumlah_sampel' => 2,
                'rencana_metode_sampling' => 'Acak',
                'status' => 'approved',
                'alasan_penolakan' => NULL,
                'created_at' => '2026-07-08 06:19:39',
                'updated_at' => '2026-07-08 06:19:39',
            ),
            17 => 
            array (
                'id' => 48,
                'user_id' => 35,
                'provinsi' => 'Aceh',
                'kab_kota' => 'Aceh Utara',
                'jenis_mp' => 'Udang Vannamei',
                'jenis_hpik' => 'WSSV, TSV, AHPND, IMNV, IHHNV, YHV, CMNV, EHP, NHP, DIV-1',
                'kemampuan_uji_upt' => 'WSSV, TSV, AHPND, IMNV, IHHNV, YHV, EHP',
                'metode_pengujian' => 'PCR Konvensional',
                'lab_uji' => 'BKHIT Aceh',
                'target_uji' => 7,
                'tw1' => 0,
                'tw2' => 7,
                'tw3' => 7,
                'tw4' => 0,
                'total_pengujian' => 14,
                'rencana_lokasi' => 'Tambak Aceh Utara',
                'rencana_jumlah_sampel' => 10,
                'rencana_metode_sampling' => 'Acak',
                'status' => 'approved',
                'alasan_penolakan' => NULL,
                'created_at' => '2026-07-08 06:19:39',
                'updated_at' => '2026-07-08 06:19:39',
            ),
            18 => 
            array (
                'id' => 49,
                'user_id' => 35,
                'provinsi' => 'Aceh',
                'kab_kota' => 'Aceh Utara',
                'jenis_mp' => 'Kerapu',
                'jenis_hpik' => 'RSIVD, VNN',
                'kemampuan_uji_upt' => 'RSIVD, VNN',
                'metode_pengujian' => 'PCR Konvensional',
                'lab_uji' => 'BKHIT Aceh',
                'target_uji' => 2,
                'tw1' => 0,
                'tw2' => 2,
                'tw3' => 2,
                'tw4' => 0,
                'total_pengujian' => 4,
                'rencana_lokasi' => 'Tambak Aceh Utara',
                'rencana_jumlah_sampel' => 2,
                'rencana_metode_sampling' => 'Acak',
                'status' => 'approved',
                'alasan_penolakan' => NULL,
                'created_at' => '2026-07-08 06:19:39',
                'updated_at' => '2026-07-08 06:19:39',
            ),
            19 => 
            array (
                'id' => 50,
                'user_id' => 35,
                'provinsi' => 'Aceh',
                'kab_kota' => 'Aceh Timur',
                'jenis_mp' => 'Udang Vannamei',
                'jenis_hpik' => 'WSSV, TSV, AHPND, IMNV, IHHNV, YHV, CMNV, EHP, NHP, DIV-1',
                'kemampuan_uji_upt' => 'WSSV, TSV, AHPND, IMNV, IHHNV, YHV, EHP',
                'metode_pengujian' => 'PCR Konvensional',
                'lab_uji' => 'BKHIT Aceh',
                'target_uji' => 7,
                'tw1' => 0,
                'tw2' => 7,
                'tw3' => 7,
                'tw4' => 0,
                'total_pengujian' => 14,
                'rencana_lokasi' => 'Tambak Aceh Timur',
                'rencana_jumlah_sampel' => 8,
                'rencana_metode_sampling' => 'Acak',
                'status' => 'approved',
                'alasan_penolakan' => NULL,
                'created_at' => '2026-07-08 06:19:39',
                'updated_at' => '2026-07-08 06:19:39',
            ),
            20 => 
            array (
                'id' => 51,
                'user_id' => 35,
                'provinsi' => 'Aceh',
                'kab_kota' => 'Aceh Timur',
                'jenis_mp' => 'Kerapu',
                'jenis_hpik' => 'RSIVD, VNN',
                'kemampuan_uji_upt' => 'RSIVD, VNN',
                'metode_pengujian' => 'PCR Konvensional',
                'lab_uji' => 'BKHIT Aceh',
                'target_uji' => 2,
                'tw1' => 0,
                'tw2' => 2,
                'tw3' => 2,
                'tw4' => 0,
                'total_pengujian' => 4,
                'rencana_lokasi' => 'Tambak Aceh Timur',
                'rencana_jumlah_sampel' => 2,
                'rencana_metode_sampling' => 'Acak',
                'status' => 'approved',
                'alasan_penolakan' => NULL,
                'created_at' => '2026-07-08 06:19:39',
                'updated_at' => '2026-07-08 06:19:39',
            ),
            21 => 
            array (
                'id' => 52,
                'user_id' => 38,
                'provinsi' => 'Jambi',
                'kab_kota' => 'Kab. Muaro Jambi',
                'jenis_mp' => 'Patin',
                'jenis_hpik' => '- Edwardsiella ictaluri - Streptococcus agalactiae',
                'kemampuan_uji_upt' => '- Edwardsiella ictaluri - Streptococcus agalactiae',
                'metode_pengujian' => 'Biokimia Konvensional',
                'lab_uji' => 'Balai KHIT Jambi',
                'target_uji' => 5,
                'tw1' => 0,
                'tw2' => 4,
                'tw3' => 4,
                'tw4' => 0,
                'total_pengujian' => 8,
                'rencana_lokasi' => '1. Benih Berkah Bersama Desa Kota Karang
2. Pokdakan ( Heru ) Desa Kota Karang Kec. Kumpeh Ulu
3. UPR Mina Sejatera Kec. Kumpeh Ilir
4. Pokdakan Bina Mandiri Kec. Jambi Luar Kota',
                'rencana_jumlah_sampel' => 16,
                'rencana_metode_sampling' => 'Acak',
                'status' => 'approved',
                'alasan_penolakan' => NULL,
                'created_at' => '2026-07-08 06:19:39',
                'updated_at' => '2026-07-08 06:19:39',
            ),
            22 => 
            array (
                'id' => 53,
                'user_id' => 38,
                'provinsi' => 'Jambi',
                'kab_kota' => 'Kab. Muaro Jambi',
                'jenis_mp' => 'Gurame, Nila',
                'jenis_hpik' => '- Aeromonas salmonicida - TiLV - EUS',
                'kemampuan_uji_upt' => '- Aeromonas salmonicida - TiLV',
                'metode_pengujian' => 'Biokimia Konvensional
PCR Konvensional',
                'lab_uji' => 'Balai KHIT Jambi',
                'target_uji' => 0,
                'tw1' => 0,
                'tw2' => 0,
                'tw3' => 0,
                'tw4' => 0,
                'total_pengujian' => 0,
                'rencana_lokasi' => '-',
                'rencana_jumlah_sampel' => 0,
                'rencana_metode_sampling' => '-',
                'status' => 'approved',
                'alasan_penolakan' => NULL,
                'created_at' => '2026-07-08 06:19:39',
                'updated_at' => '2026-07-08 06:19:39',
            ),
            23 => 
            array (
                'id' => 54,
                'user_id' => 38,
                'provinsi' => 'Jambi',
                'kab_kota' => 'Kab. Batanghari',
                'jenis_mp' => 'Patin',
                'jenis_hpik' => '- Edwardsiella ictaluri - Streptococcus agalactiae - Aeromonas salmonicida - TiLV',
                'kemampuan_uji_upt' => 'Edwardsiella ictaluri, Streptococcus agalactiae',
                'metode_pengujian' => 'Biokimia Konvensional',
                'lab_uji' => 'Balai KHIT Jambi',
                'target_uji' => 4,
                'tw1' => 0,
                'tw2' => 4,
                'tw3' => 4,
                'tw4' => 0,
                'total_pengujian' => 8,
                'rencana_lokasi' => '1. Pokdakan Mekar Bersama Desa Aro-Kec. Pemayung
2. Pokdakan Rifai Desa Jembatan Mas
3. Bapak Oman Sulaiman Desa Muaro Singoan Kec. Muara Bulian',
                'rencana_jumlah_sampel' => 16,
                'rencana_metode_sampling' => 'Acak',
                'status' => 'approved',
                'alasan_penolakan' => NULL,
                'created_at' => '2026-07-08 06:19:39',
                'updated_at' => '2026-07-08 06:19:39',
            ),
            24 => 
            array (
                'id' => 55,
                'user_id' => 38,
                'provinsi' => 'Jambi',
                'kab_kota' => 'Kab. Tanjung Jabung Barat',
                'jenis_mp' => 'Lele, Patin, Nila',
                'jenis_hpik' => '- Edwardsiella ictaluri - A. salmonicida - S. agalactiae - Yersinia ruckeri - S. iniae - A. invadans - TiLV',
                'kemampuan_uji_upt' => '- E. Ictaluri - A. salmonicida - S. agalactiae - Yersinia ruckeri - S. iniae - S. invadans - TiLV',
                'metode_pengujian' => 'Biokimia, PCR Konvensional',
                'lab_uji' => 'Balai KHIT Jambi',
                'target_uji' => 7,
                'tw1' => 0,
                'tw2' => 7,
                'tw3' => 7,
                'tw4' => 0,
                'total_pengujian' => 14,
                'rencana_lokasi' => '1. Pokdakan Tunas Kencana Desa Tungkal Harapan Kec. Tungkal Ilir
2. Pokdakan Bram Itam Desa Pembengis Kec. Bram Itam
3. UPT PBATAP Desa Pembengis Kec. Bram Itam',
                'rencana_jumlah_sampel' => 16,
                'rencana_metode_sampling' => 'Acak',
                'status' => 'approved',
                'alasan_penolakan' => NULL,
                'created_at' => '2026-07-08 06:19:39',
                'updated_at' => '2026-07-08 06:19:39',
            ),
            25 => 
            array (
                'id' => 56,
                'user_id' => 38,
                'provinsi' => 'Jambi',
                'kab_kota' => 'Kab. Tanjung Jabung Timur',
                'jenis_mp' => 'Lele, Patin, Nila',
                'jenis_hpik' => '- Edwardsiella ictaluri - Aeromonas salmonicida - Streptococcus agalactiae - Yersinia ruckeri - Streptococcus iniae - Aphanomyces invadans - TiLV',
                'kemampuan_uji_upt' => '- Edwardsiella ictaluri - Aeromonas salmonicida - Streptococcus agalactiae - Yersinia ruckeri - Streptococcus iniae - A. invadans - TiLV',
                'metode_pengujian' => 'Biokimia, PCR Konvensional',
                'lab_uji' => 'Balai KHIT Jambi',
                'target_uji' => 7,
                'tw1' => 0,
                'tw2' => 7,
                'tw3' => 7,
                'tw4' => 0,
                'total_pengujian' => 14,
                'rencana_lokasi' => '1. Pokdakan Berkat Usaha Kec. Muara Sabak Barat
2. Pokdakan Mina Karya Abadi Bapak Taufik Desa/Kec. Nipah Putih
3. Pokdakan Rezeki Alam Kec. Muara Sabak Barat
4. UPR Bpk. Roni Kel. Parit Culum II',
                'rencana_jumlah_sampel' => 16,
                'rencana_metode_sampling' => 'Acak',
                'status' => 'approved',
                'alasan_penolakan' => NULL,
                'created_at' => '2026-07-08 06:19:39',
                'updated_at' => '2026-07-08 06:19:39',
            ),
            26 => 
            array (
                'id' => 57,
                'user_id' => 38,
                'provinsi' => 'Jambi',
                'kab_kota' => 'Kab. Tebo',
                'jenis_mp' => 'Lele, Nila',
                'jenis_hpik' => '- Edwardsiella ictaluri - Aeromonas salmonicida - Yersinia ruckeri - Streptococcus agalactiae - Aphanomyces invadans - TiLV',
                'kemampuan_uji_upt' => '- Edwardsiella ictaluri - Aeromonas salmonicida - Yersinia ruckeri - Streptococcus agalactiae - Aphanomyces invadans - TiLV',
                'metode_pengujian' => 'Biokimia, PCR Konvensional',
                'lab_uji' => 'Balai KHIT Jambi',
                'target_uji' => 6,
                'tw1' => 0,
                'tw2' => 6,
                'tw3' => 6,
                'tw4' => 0,
                'total_pengujian' => 12,
                'rencana_lokasi' => '1. BBI Sungai Alai Kec. Sungai Alai
2. Pokdakan Cahaya Mandiri dan Madep Ngarep Desa Sari Mulya Kecamatan Rimbo
3. UPR Bpk. Hambali Kec. Tebo Tengah
4. Pokdakan Sepakat Maju Ture Kec. Bedaro Rampak',
                'rencana_jumlah_sampel' => 16,
                'rencana_metode_sampling' => 'Acak',
                'status' => 'approved',
                'alasan_penolakan' => NULL,
                'created_at' => '2026-07-08 06:19:39',
                'updated_at' => '2026-07-08 06:19:39',
            ),
            27 => 
            array (
                'id' => 58,
                'user_id' => 38,
                'provinsi' => 'Jambi',
                'kab_kota' => 'Kab. Bungo',
                'jenis_mp' => 'Lele, Patin, Nila',
                'jenis_hpik' => '- Edwardsiella ictaluri - Aeromonas salmonicida - Streptococcus agalactiae - Yersinia ruckeri - Streptococcus iniae - Aphanomyces invadans - TiLV',
                'kemampuan_uji_upt' => '- Edwardsiella ictaluri - Aeromonas salmonicida - S. agalactiae - Yersinia ruckeri - Streptococcus iniae - A. invadans - TiLV',
                'metode_pengujian' => 'Biokimia, PCR Konvensional',
                'lab_uji' => 'Balai KHIT Jambi',
                'target_uji' => 7,
                'tw1' => 0,
                'tw2' => 7,
                'tw3' => 7,
                'tw4' => 0,
                'total_pengujian' => 14,
                'rencana_lokasi' => '1. Pokdakan Karya Mina Desa Sungai Kerjan Kec Muara Bungo
2. UPR Sumber Makmur
3. UPR Harjo Makmur
4. UPR Sumber',
                'rencana_jumlah_sampel' => 16,
                'rencana_metode_sampling' => 'Acak',
                'status' => 'approved',
                'alasan_penolakan' => NULL,
                'created_at' => '2026-07-08 06:19:39',
                'updated_at' => '2026-07-08 06:19:39',
            ),
            28 => 
            array (
                'id' => 59,
                'user_id' => 38,
                'provinsi' => 'Jambi',
                'kab_kota' => 'Kab. Sarolangun',
                'jenis_mp' => 'Lele, Patin, Nila',
                'jenis_hpik' => '- Edwardsiella ictaluri - Aeromonas salmonicida - Yersinia ruckeri - Streptococcus agalactiae - Aphanomyces invadans',
                'kemampuan_uji_upt' => '- Edwardsiella ictaluri - Aeromonas salmonicida - Yersinia ruckeri - Streptococcus agalactiae - Aphanomyces invadans',
                'metode_pengujian' => 'Biokimia, PCR Konvensional',
                'lab_uji' => 'Balai KHIT Jambi',
                'target_uji' => 5,
                'tw1' => 0,
                'tw2' => 5,
                'tw3' => 5,
                'tw4' => 0,
                'total_pengujian' => 10,
                'rencana_lokasi' => '1. Pokdakan Doa Ibu Desa Bukit Talang Mas Kec. Singkut
2. UPR Hadi Rahayu Bukit Talang Mas
3. BBI Singkut Kecamatan Singkut
4. Pokdakan Sumber Rezeki Kec. Singku',
                'rencana_jumlah_sampel' => 16,
                'rencana_metode_sampling' => 'Acak',
                'status' => 'approved',
                'alasan_penolakan' => NULL,
                'created_at' => '2026-07-08 06:19:39',
                'updated_at' => '2026-07-08 06:19:39',
            ),
            29 => 
            array (
                'id' => 60,
                'user_id' => 38,
                'provinsi' => 'Jambi',
                'kab_kota' => 'Kab. Merangin',
                'jenis_mp' => 'Lele, Patin, Nila',
                'jenis_hpik' => '- Edwardsiella ictaluri - A. salmonicida - S. agalactiae - Yersinia ruckeri - S. iniae - Aphanomyces invadans - TiLV',
                'kemampuan_uji_upt' => '- Edwardsiella ictaluri - A. salmonicida - S. agalactiae - Yersinia ruckeri - S. iniae - A. invadans - TiLV',
                'metode_pengujian' => 'Biokimia, PCR Konvensional',
                'lab_uji' => 'Balai KHIT Jambi',
                'target_uji' => 7,
                'tw1' => 0,
                'tw2' => 7,
                'tw3' => 7,
                'tw4' => 0,
                'total_pengujian' => 14,
                'rencana_lokasi' => '1. UPTD BBAT Bangko ; Desa Talang Kawo
2. Pokdakan Adzikra Bpk Sukri Desa Sungai Ulak Kecamatan Nala Tanta
3. Pokdakan Suka Maju Dusun Bangko Kecamatan Talang Kawo
4. BBI Talang Kawo Dusun Bangko Kecamatan Talang Kawo',
                'rencana_jumlah_sampel' => 16,
                'rencana_metode_sampling' => 'Acak',
                'status' => 'approved',
                'alasan_penolakan' => NULL,
                'created_at' => '2026-07-08 06:19:39',
                'updated_at' => '2026-07-08 06:19:39',
            ),
            30 => 
            array (
                'id' => 61,
                'user_id' => 38,
                'provinsi' => 'Jambi',
                'kab_kota' => 'Kerinci',
                'jenis_mp' => 'Mas, Jelawat, Nila Lele',
                'jenis_hpik' => '- Edwardsiella ictaluri - A. salmonicida - Yersinia ruckeri - Streptococcus agalactiae - Aphanomyces invadans - TiLV - KHV - SVCV - CEV',
                'kemampuan_uji_upt' => '- Edwardsiella ictaluri - Aeromonas salmonicida - Yersinia ruckeri - Streptococcus agalactiae - Aphanomyces invadans - TiLV - KHV - SVCV - CEV',
                'metode_pengujian' => 'Biokimia, PCR Konvensional',
                'lab_uji' => 'Balai KHIT Jambi',
                'target_uji' => 9,
                'tw1' => 0,
                'tw2' => 7,
                'tw3' => 7,
                'tw4' => 0,
                'total_pengujian' => 14,
                'rencana_lokasi' => '1. Pokdakan Mina Mandiri Desa Siulak Kecil Hilir Kec. Siulak
2. Pokdakan Tugu Sakti Desa Air Panas Kecamatan Air Panas
3. BBI Semurup Desa Pendung Semurup Kecamatan Air Hangat',
                'rencana_jumlah_sampel' => 16,
                'rencana_metode_sampling' => 'Acak',
                'status' => 'approved',
                'alasan_penolakan' => NULL,
                'created_at' => '2026-07-08 06:19:39',
                'updated_at' => '2026-07-08 06:19:39',
            ),
            31 => 
            array (
                'id' => 62,
                'user_id' => 46,
                'provinsi' => 'Jawa Tengah',
                'kab_kota' => 'Kabupaten Kebumen',
                'jenis_mp' => 'Udang Vannamei',
                'jenis_hpik' => 'IHHNV, YHV, TSV, WSSV, IMNV, CMNV, DIV-1, AHPND, NHP, EHP',
                'kemampuan_uji_upt' => 'IHHNV, YHV, TSV, WSSV, IMNV, CMNV, DIV-1, AHPND, NHP, EHP',
                'metode_pengujian' => 'PCR Konvensional',
                'lab_uji' => 'Balai KHIT Jawa Tengah',
                'target_uji' => 10,
                'tw1' => 10,
                'tw2' => 0,
                'tw3' => 10,
                'tw4' => 0,
                'total_pengujian' => 20,
            'rencana_lokasi' => 'Budidaya Udang Berbasis Kawasan (BUBK) KKP Jogjaretno, Kec. Petanahan, Kab. Kebumen',
                'rencana_jumlah_sampel' => 30,
                'rencana_metode_sampling' => 'acak',
                'status' => 'approved',
                'alasan_penolakan' => NULL,
                'created_at' => '2026-07-08 13:52:05',
                'updated_at' => '2026-07-08 13:52:05',
            ),
            32 => 
            array (
                'id' => 63,
                'user_id' => 46,
                'provinsi' => 'Jawa Tengah',
                'kab_kota' => 'Kabupaten Kendal',
                'jenis_mp' => 'Udang Vannamei',
                'jenis_hpik' => 'IHHNV, YHV, TSV, WSSV, IMNV, CMNV, DIV-1, AHPND, NHP, EHP',
                'kemampuan_uji_upt' => 'IHHNV, YHV, TSV, WSSV, IMNV, CMNV, DIV-1, AHPND, NHP, EHP',
                'metode_pengujian' => 'PCR Konvensional',
                'lab_uji' => 'Balai KHIT Jawa Tengah',
                'target_uji' => 10,
                'tw1' => 10,
                'tw2' => 0,
                'tw3' => 10,
                'tw4' => 0,
                'total_pengujian' => 20,
                'rencana_lokasi' => 'Karangsari, Berahmalia, Kec Kendal dan Karangkambang, Gg Cirebo RT 05/RW 03 Kendal',
                'rencana_jumlah_sampel' => 30,
                'rencana_metode_sampling' => 'acak',
                'status' => 'approved',
                'alasan_penolakan' => NULL,
                'created_at' => '2026-07-08 13:52:05',
                'updated_at' => '2026-07-08 13:52:05',
            ),
            33 => 
            array (
                'id' => 64,
                'user_id' => 46,
                'provinsi' => 'Jawa Tengah',
                'kab_kota' => 'Kabupaten Pati',
                'jenis_mp' => 'Udang Vannamei',
                'jenis_hpik' => 'IHHNV, YHV, TSV, WSSV, IMNV, CMNV, DIV-1, AHPND, NHP, EHP',
                'kemampuan_uji_upt' => 'IHHNV, YHV, TSV, WSSV, IMNV, CMNV, DIV-1, AHPND, NHP, EHP',
                'metode_pengujian' => 'PCR Konvensional',
                'lab_uji' => 'Balai KHIT Jawa Tengah',
                'target_uji' => 10,
                'tw1' => 10,
                'tw2' => 0,
                'tw3' => 10,
                'tw4' => 0,
                'total_pengujian' => 20,
                'rencana_lokasi' => 'Podakan Mina Barokah Ds. Sambiroto, Kec. Tayu, Kab. Pati dan Desa Sendangrejo, Kec. Juwana, Kab. Pati',
                'rencana_jumlah_sampel' => 30,
                'rencana_metode_sampling' => 'acak',
                'status' => 'approved',
                'alasan_penolakan' => NULL,
                'created_at' => '2026-07-08 13:52:05',
                'updated_at' => '2026-07-08 13:52:05',
            ),
            34 => 
            array (
                'id' => 65,
                'user_id' => 67,
                'provinsi' => 'Papua Pegunungan',
                'kab_kota' => 'Kabupaten Jayawijaya',
                'jenis_mp' => 'Nila',
                'jenis_hpik' => 'TiLV, Aeromonas salmonicida',
                'kemampuan_uji_upt' => 'Belum Dapat melakukan pengujian',
                'metode_pengujian' => '-',
            'lab_uji' => 'BKHIT Papua Barat Daya, BBKHIT Papua (TiLV, ESC), BKHIT Papua Selatan (Streptococcus iniae), BEUBKHIT',
                'target_uji' => 8,
                'tw1' => 1,
                'tw2' => 0,
                'tw3' => 1,
                'tw4' => 0,
                'total_pengujian' => 2,
                'rencana_lokasi' => 'UPR Kab. Jayawijaya',
                'rencana_jumlah_sampel' => 10,
                'rencana_metode_sampling' => 'acak',
                'status' => 'approved',
                'alasan_penolakan' => NULL,
                'created_at' => '2026-07-08 13:52:05',
                'updated_at' => '2026-07-08 13:52:05',
            ),
            35 => 
            array (
                'id' => 66,
                'user_id' => 67,
                'provinsi' => 'Papua Pegunungan',
                'kab_kota' => 'Kabupaten Jayawijaya',
                'jenis_mp' => 'Mas',
                'jenis_hpik' => 'KHV, Aeromonas salmonicida',
                'kemampuan_uji_upt' => 'Belum Dapat melakukan pengujian',
                'metode_pengujian' => '-',
            'lab_uji' => 'BKHIT Papua Barat Daya, BBKHIT Papua (KHV), BKHIT Papua Selatan (SVCV)',
                'target_uji' => 6,
                'tw1' => 1,
                'tw2' => 0,
                'tw3' => 1,
                'tw4' => 0,
                'total_pengujian' => 2,
                'rencana_lokasi' => 'UPR Kab. Jayawijaya',
                'rencana_jumlah_sampel' => 10,
                'rencana_metode_sampling' => 'acak',
                'status' => 'approved',
                'alasan_penolakan' => NULL,
                'created_at' => '2026-07-08 13:52:05',
                'updated_at' => '2026-07-08 13:52:05',
            ),
        ));
        
        
    }
}