<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class UsersTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('users')->delete();
        
        \DB::table('users')->insert(array (
            0 => 
            array (
                'id' => 25,
                'parent_id' => NULL,
                'name' => 'Developer',
                'email' => 'developer@system.local',
                'role' => 'developer',
                'upt_asal' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$ECwVO3.6IgFhAPyXCaJ5dOdQqCkDSnLHoqo7kK2dh5qtcCHibygIa',
                'remember_token' => 's16sLgHYvUBFGskSw4zp044bSaYkiYkFFmIpDeHiqLIW5mWvJMYVfkT0bMKa',
                'created_at' => '2026-07-07 14:52:19',
                'updated_at' => '2026-07-07 14:52:19',
            ),
            1 => 
            array (
                'id' => 26,
                'parent_id' => NULL,
                'name' => 'Admin Pusat',
                'email' => 'adminpusat@gmail.com',
                'role' => 'pusat',
                'upt_asal' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$L.8jPcQCEFOxzFAda4tiU.pjdqEsrKz3Cihh/chjCHqxN5p8ny1xK',
                'remember_token' => NULL,
                'created_at' => '2026-07-07 15:03:30',
                'updated_at' => '2026-07-07 15:03:30',
            ),
            2 => 
            array (
                'id' => 27,
                'parent_id' => NULL,
                'name' => 'BUSKHIT',
                'email' => 'buskhit@gmail.com',
                'role' => 'bbkhit',
                'upt_asal' => 'BUSKHIT',
                'email_verified_at' => NULL,
                'password' => '$2y$12$L.8jPcQCEFOxzFAda4tiU.pjdqEsrKz3Cihh/chjCHqxN5p8ny1xK',
                'remember_token' => NULL,
                'created_at' => '2026-07-07 15:03:30',
                'updated_at' => '2026-07-07 15:03:30',
            ),
            3 => 
            array (
                'id' => 28,
                'parent_id' => NULL,
                'name' => 'BUTTMKHIT',
                'email' => 'buttmkhit@gmail.com',
                'role' => 'bbkhit',
                'upt_asal' => 'BUTTMKHIT',
                'email_verified_at' => NULL,
                'password' => '$2y$12$L.8jPcQCEFOxzFAda4tiU.pjdqEsrKz3Cihh/chjCHqxN5p8ny1xK',
                'remember_token' => NULL,
                'created_at' => '2026-07-07 15:03:30',
                'updated_at' => '2026-07-07 15:03:30',
            ),
            4 => 
            array (
                'id' => 29,
                'parent_id' => NULL,
                'name' => 'BBKHIT Soekarno-Hatta',
                'email' => 'bbkhitsoekarnohatta@gmail.com',
                'role' => 'bbkhit',
                'upt_asal' => 'BBKHIT Soekarno-Hatta',
                'email_verified_at' => NULL,
                'password' => '$2y$12$L.8jPcQCEFOxzFAda4tiU.pjdqEsrKz3Cihh/chjCHqxN5p8ny1xK',
                'remember_token' => NULL,
                'created_at' => '2026-07-07 15:03:30',
                'updated_at' => '2026-07-07 15:03:30',
            ),
            5 => 
            array (
                'id' => 30,
                'parent_id' => NULL,
                'name' => 'BBKHIT Tanjung Priok',
                'email' => 'bbkhittanjungpriok@gmail.com',
                'role' => 'bbkhit',
                'upt_asal' => 'BBKHIT Tanjung Priok',
                'email_verified_at' => NULL,
                'password' => '$2y$12$L.8jPcQCEFOxzFAda4tiU.pjdqEsrKz3Cihh/chjCHqxN5p8ny1xK',
                'remember_token' => NULL,
                'created_at' => '2026-07-07 15:03:30',
                'updated_at' => '2026-07-07 15:03:30',
            ),
            6 => 
            array (
                'id' => 31,
                'parent_id' => NULL,
                'name' => 'BBKHIT Sumatera Utara',
                'email' => 'bbkhitsumaterautara@gmail.com',
                'role' => 'bbkhit',
                'upt_asal' => 'BBKHIT Sumatera Utara',
                'email_verified_at' => NULL,
                'password' => '$2y$12$L.8jPcQCEFOxzFAda4tiU.pjdqEsrKz3Cihh/chjCHqxN5p8ny1xK',
                'remember_token' => NULL,
                'created_at' => '2026-07-07 15:03:30',
                'updated_at' => '2026-07-07 15:03:30',
            ),
            7 => 
            array (
                'id' => 32,
                'parent_id' => NULL,
                'name' => 'BBKHIT Jawa Timur',
                'email' => 'bbkhitjawatimur@gmail.com',
                'role' => 'bbkhit',
                'upt_asal' => 'BBKHIT Jawa Timur',
                'email_verified_at' => NULL,
                'password' => '$2y$12$L.8jPcQCEFOxzFAda4tiU.pjdqEsrKz3Cihh/chjCHqxN5p8ny1xK',
                'remember_token' => NULL,
                'created_at' => '2026-07-07 15:03:30',
                'updated_at' => '2026-07-07 15:03:30',
            ),
            8 => 
            array (
                'id' => 33,
                'parent_id' => NULL,
                'name' => 'BBKHIT Sulawesi Selatan',
                'email' => 'bbkhitsulawesiselatan@gmail.com',
                'role' => 'bbkhit',
                'upt_asal' => 'BBKHIT Sulawesi Selatan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$L.8jPcQCEFOxzFAda4tiU.pjdqEsrKz3Cihh/chjCHqxN5p8ny1xK',
                'remember_token' => NULL,
                'created_at' => '2026-07-07 15:03:30',
                'updated_at' => '2026-07-07 15:03:30',
            ),
            9 => 
            array (
                'id' => 34,
                'parent_id' => NULL,
                'name' => 'BBKHIT Papua',
                'email' => 'bbkhitpapua@gmail.com',
                'role' => 'bbkhit',
                'upt_asal' => 'BBKHIT Papua',
                'email_verified_at' => NULL,
                'password' => '$2y$12$L.8jPcQCEFOxzFAda4tiU.pjdqEsrKz3Cihh/chjCHqxN5p8ny1xK',
                'remember_token' => NULL,
                'created_at' => '2026-07-07 15:03:30',
                'updated_at' => '2026-07-07 15:03:30',
            ),
            10 => 
            array (
                'id' => 35,
                'parent_id' => NULL,
                'name' => 'BKHIT Aceh',
                'email' => 'bkhitaceh@gmail.com',
                'role' => 'bkhit',
                'upt_asal' => 'BKHIT Aceh',
                'email_verified_at' => NULL,
                'password' => '$2y$12$L.8jPcQCEFOxzFAda4tiU.pjdqEsrKz3Cihh/chjCHqxN5p8ny1xK',
                'remember_token' => NULL,
                'created_at' => '2026-07-07 15:03:30',
                'updated_at' => '2026-07-07 15:03:30',
            ),
            11 => 
            array (
                'id' => 36,
                'parent_id' => NULL,
                'name' => 'BKHIT Riau',
                'email' => 'bkhitriau@gmail.com',
                'role' => 'bkhit',
                'upt_asal' => 'BKHIT Riau',
                'email_verified_at' => NULL,
                'password' => '$2y$12$L.8jPcQCEFOxzFAda4tiU.pjdqEsrKz3Cihh/chjCHqxN5p8ny1xK',
                'remember_token' => NULL,
                'created_at' => '2026-07-07 15:03:30',
                'updated_at' => '2026-07-07 15:03:30',
            ),
            12 => 
            array (
                'id' => 37,
                'parent_id' => NULL,
                'name' => 'BKHIT Kepulauan Riau',
                'email' => 'bkhitkepulauanriau@gmail.com',
                'role' => 'bkhit',
                'upt_asal' => 'BKHIT Kepulauan Riau',
                'email_verified_at' => NULL,
                'password' => '$2y$12$L.8jPcQCEFOxzFAda4tiU.pjdqEsrKz3Cihh/chjCHqxN5p8ny1xK',
                'remember_token' => NULL,
                'created_at' => '2026-07-07 15:03:30',
                'updated_at' => '2026-07-07 15:03:30',
            ),
            13 => 
            array (
                'id' => 38,
                'parent_id' => NULL,
                'name' => 'BKHIT Jambi',
                'email' => 'bkhitjambi@gmail.com',
                'role' => 'bkhit',
                'upt_asal' => 'BKHIT Jambi',
                'email_verified_at' => NULL,
                'password' => '$2y$12$L.8jPcQCEFOxzFAda4tiU.pjdqEsrKz3Cihh/chjCHqxN5p8ny1xK',
                'remember_token' => NULL,
                'created_at' => '2026-07-07 15:03:30',
                'updated_at' => '2026-07-07 15:03:30',
            ),
            14 => 
            array (
                'id' => 39,
                'parent_id' => NULL,
                'name' => 'BKHIT Sumatera Barat',
                'email' => 'bkhitsumaterabarat@gmail.com',
                'role' => 'bkhit',
                'upt_asal' => 'BKHIT Sumatera Barat',
                'email_verified_at' => NULL,
                'password' => '$2y$12$L.8jPcQCEFOxzFAda4tiU.pjdqEsrKz3Cihh/chjCHqxN5p8ny1xK',
                'remember_token' => NULL,
                'created_at' => '2026-07-07 15:03:30',
                'updated_at' => '2026-07-07 15:03:30',
            ),
            15 => 
            array (
                'id' => 40,
                'parent_id' => NULL,
                'name' => 'BKHIT Sumatera Selatan',
                'email' => 'bkhitsumateraselatan@gmail.com',
                'role' => 'bkhit',
                'upt_asal' => 'BKHIT Sumatera Selatan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$L.8jPcQCEFOxzFAda4tiU.pjdqEsrKz3Cihh/chjCHqxN5p8ny1xK',
                'remember_token' => NULL,
                'created_at' => '2026-07-07 15:03:30',
                'updated_at' => '2026-07-07 15:03:30',
            ),
            16 => 
            array (
                'id' => 41,
                'parent_id' => NULL,
                'name' => 'BKHIT Kepulauan Bangka Belitung',
                'email' => 'bkhitkepulauanbangkabelitung@gmail.com',
                'role' => 'bkhit',
                'upt_asal' => 'BKHIT Kepulauan Bangka Belitung',
                'email_verified_at' => NULL,
                'password' => '$2y$12$L.8jPcQCEFOxzFAda4tiU.pjdqEsrKz3Cihh/chjCHqxN5p8ny1xK',
                'remember_token' => NULL,
                'created_at' => '2026-07-07 15:03:30',
                'updated_at' => '2026-07-07 15:03:30',
            ),
            17 => 
            array (
                'id' => 42,
                'parent_id' => NULL,
                'name' => 'BKHIT Bengkulu',
                'email' => 'bkhitbengkulu@gmail.com',
                'role' => 'bkhit',
                'upt_asal' => 'BKHIT Bengkulu',
                'email_verified_at' => NULL,
                'password' => '$2y$12$L.8jPcQCEFOxzFAda4tiU.pjdqEsrKz3Cihh/chjCHqxN5p8ny1xK',
                'remember_token' => NULL,
                'created_at' => '2026-07-07 15:03:30',
                'updated_at' => '2026-07-07 15:03:30',
            ),
            18 => 
            array (
                'id' => 43,
                'parent_id' => NULL,
                'name' => 'BKHIT Lampung',
                'email' => 'bkhitlampung@gmail.com',
                'role' => 'bkhit',
                'upt_asal' => 'BKHIT Lampung',
                'email_verified_at' => NULL,
                'password' => '$2y$12$L.8jPcQCEFOxzFAda4tiU.pjdqEsrKz3Cihh/chjCHqxN5p8ny1xK',
                'remember_token' => NULL,
                'created_at' => '2026-07-07 15:03:30',
                'updated_at' => '2026-07-07 15:03:30',
            ),
            19 => 
            array (
                'id' => 44,
                'parent_id' => NULL,
                'name' => 'BKHIT Banten',
                'email' => 'bkhitbanten@gmail.com',
                'role' => 'bkhit',
                'upt_asal' => 'BKHIT Banten',
                'email_verified_at' => NULL,
                'password' => '$2y$12$L.8jPcQCEFOxzFAda4tiU.pjdqEsrKz3Cihh/chjCHqxN5p8ny1xK',
                'remember_token' => NULL,
                'created_at' => '2026-07-07 15:03:30',
                'updated_at' => '2026-07-07 15:03:30',
            ),
            20 => 
            array (
                'id' => 45,
                'parent_id' => NULL,
                'name' => 'BKHIT Jawa Barat',
                'email' => 'bkhitjawabarat@gmail.com',
                'role' => 'bkhit',
                'upt_asal' => 'BKHIT Jawa Barat',
                'email_verified_at' => NULL,
                'password' => '$2y$12$L.8jPcQCEFOxzFAda4tiU.pjdqEsrKz3Cihh/chjCHqxN5p8ny1xK',
                'remember_token' => NULL,
                'created_at' => '2026-07-07 15:03:30',
                'updated_at' => '2026-07-07 15:03:30',
            ),
            21 => 
            array (
                'id' => 46,
                'parent_id' => NULL,
                'name' => 'BKHIT Jawa Tengah',
                'email' => 'bkhitjawatengah@gmail.com',
                'role' => 'bkhit',
                'upt_asal' => 'BKHIT Jawa Tengah',
                'email_verified_at' => NULL,
                'password' => '$2y$12$L.8jPcQCEFOxzFAda4tiU.pjdqEsrKz3Cihh/chjCHqxN5p8ny1xK',
                'remember_token' => NULL,
                'created_at' => '2026-07-07 15:03:30',
                'updated_at' => '2026-07-07 15:03:30',
            ),
            22 => 
            array (
                'id' => 47,
                'parent_id' => NULL,
                'name' => 'BKHIT DI Yogyakarta',
                'email' => 'bkhitdiyogyakarta@gmail.com',
                'role' => 'bkhit',
                'upt_asal' => 'BKHIT DI Yogyakarta',
                'email_verified_at' => NULL,
                'password' => '$2y$12$L.8jPcQCEFOxzFAda4tiU.pjdqEsrKz3Cihh/chjCHqxN5p8ny1xK',
                'remember_token' => NULL,
                'created_at' => '2026-07-07 15:03:30',
                'updated_at' => '2026-07-07 15:03:30',
            ),
            23 => 
            array (
                'id' => 48,
                'parent_id' => NULL,
                'name' => 'BKHIT Bali',
                'email' => 'bkhitbali@gmail.com',
                'role' => 'bkhit',
                'upt_asal' => 'BKHIT Bali',
                'email_verified_at' => NULL,
                'password' => '$2y$12$L.8jPcQCEFOxzFAda4tiU.pjdqEsrKz3Cihh/chjCHqxN5p8ny1xK',
                'remember_token' => NULL,
                'created_at' => '2026-07-07 15:03:30',
                'updated_at' => '2026-07-07 15:03:30',
            ),
            24 => 
            array (
                'id' => 49,
                'parent_id' => NULL,
                'name' => 'BKHIT Nusa Tenggara Barat',
                'email' => 'bkhitnusatenggarabarat@gmail.com',
                'role' => 'bkhit',
                'upt_asal' => 'BKHIT Nusa Tenggara Barat',
                'email_verified_at' => NULL,
                'password' => '$2y$12$L.8jPcQCEFOxzFAda4tiU.pjdqEsrKz3Cihh/chjCHqxN5p8ny1xK',
                'remember_token' => NULL,
                'created_at' => '2026-07-07 15:03:30',
                'updated_at' => '2026-07-07 15:03:30',
            ),
            25 => 
            array (
                'id' => 50,
                'parent_id' => NULL,
                'name' => 'BKHIT Nusa Tenggara Timur',
                'email' => 'bkhitnusatenggaratimur@gmail.com',
                'role' => 'bkhit',
                'upt_asal' => 'BKHIT Nusa Tenggara Timur',
                'email_verified_at' => NULL,
                'password' => '$2y$12$L.8jPcQCEFOxzFAda4tiU.pjdqEsrKz3Cihh/chjCHqxN5p8ny1xK',
                'remember_token' => NULL,
                'created_at' => '2026-07-07 15:03:30',
                'updated_at' => '2026-07-07 15:03:30',
            ),
            26 => 
            array (
                'id' => 51,
                'parent_id' => NULL,
                'name' => 'BKHIT Kalimantan Barat',
                'email' => 'bkhitkalimantanbarat@gmail.com',
                'role' => 'bkhit',
                'upt_asal' => 'BKHIT Kalimantan Barat',
                'email_verified_at' => NULL,
                'password' => '$2y$12$L.8jPcQCEFOxzFAda4tiU.pjdqEsrKz3Cihh/chjCHqxN5p8ny1xK',
                'remember_token' => NULL,
                'created_at' => '2026-07-07 15:03:30',
                'updated_at' => '2026-07-07 15:03:30',
            ),
            27 => 
            array (
                'id' => 52,
                'parent_id' => NULL,
                'name' => 'BKHIT Kalimantan Tengah',
                'email' => 'bkhitkalimantantengah@gmail.com',
                'role' => 'bkhit',
                'upt_asal' => 'BKHIT Kalimantan Tengah',
                'email_verified_at' => NULL,
                'password' => '$2y$12$L.8jPcQCEFOxzFAda4tiU.pjdqEsrKz3Cihh/chjCHqxN5p8ny1xK',
                'remember_token' => NULL,
                'created_at' => '2026-07-07 15:03:30',
                'updated_at' => '2026-07-07 15:03:30',
            ),
            28 => 
            array (
                'id' => 53,
                'parent_id' => NULL,
                'name' => 'BKHIT Kalimantan Selatan',
                'email' => 'bkhitkalimantanselatan@gmail.com',
                'role' => 'bkhit',
                'upt_asal' => 'BKHIT Kalimantan Selatan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$L.8jPcQCEFOxzFAda4tiU.pjdqEsrKz3Cihh/chjCHqxN5p8ny1xK',
                'remember_token' => NULL,
                'created_at' => '2026-07-07 15:03:30',
                'updated_at' => '2026-07-07 15:03:30',
            ),
            29 => 
            array (
                'id' => 54,
                'parent_id' => NULL,
                'name' => 'BKHIT Kalimantan Timur',
                'email' => 'bkhitkalimantantimur@gmail.com',
                'role' => 'bkhit',
                'upt_asal' => 'BKHIT Kalimantan Timur',
                'email_verified_at' => NULL,
                'password' => '$2y$12$L.8jPcQCEFOxzFAda4tiU.pjdqEsrKz3Cihh/chjCHqxN5p8ny1xK',
                'remember_token' => NULL,
                'created_at' => '2026-07-07 15:03:30',
                'updated_at' => '2026-07-07 15:03:30',
            ),
            30 => 
            array (
                'id' => 55,
                'parent_id' => NULL,
                'name' => 'BKHIT Kalimantan Utara',
                'email' => 'bkhitkalimantanutara@gmail.com',
                'role' => 'bkhit',
                'upt_asal' => 'BKHIT Kalimantan Utara',
                'email_verified_at' => NULL,
                'password' => '$2y$12$L.8jPcQCEFOxzFAda4tiU.pjdqEsrKz3Cihh/chjCHqxN5p8ny1xK',
                'remember_token' => NULL,
                'created_at' => '2026-07-07 15:03:30',
                'updated_at' => '2026-07-07 15:03:30',
            ),
            31 => 
            array (
                'id' => 56,
                'parent_id' => NULL,
                'name' => 'BKHIT Sulawesi Utara',
                'email' => 'bkhitsulawesiutara@gmail.com',
                'role' => 'bkhit',
                'upt_asal' => 'BKHIT Sulawesi Utara',
                'email_verified_at' => NULL,
                'password' => '$2y$12$L.8jPcQCEFOxzFAda4tiU.pjdqEsrKz3Cihh/chjCHqxN5p8ny1xK',
                'remember_token' => NULL,
                'created_at' => '2026-07-07 15:03:30',
                'updated_at' => '2026-07-07 15:03:30',
            ),
            32 => 
            array (
                'id' => 57,
                'parent_id' => NULL,
                'name' => 'BKHIT Gorontalo',
                'email' => 'bkhitgorontalo@gmail.com',
                'role' => 'bkhit',
                'upt_asal' => 'BKHIT Gorontalo',
                'email_verified_at' => NULL,
                'password' => '$2y$12$L.8jPcQCEFOxzFAda4tiU.pjdqEsrKz3Cihh/chjCHqxN5p8ny1xK',
                'remember_token' => NULL,
                'created_at' => '2026-07-07 15:03:30',
                'updated_at' => '2026-07-07 15:03:30',
            ),
            33 => 
            array (
                'id' => 58,
                'parent_id' => NULL,
                'name' => 'BKHIT Sulawesi Tengah',
                'email' => 'bkhitsulawesitengah@gmail.com',
                'role' => 'bkhit',
                'upt_asal' => 'BKHIT Sulawesi Tengah',
                'email_verified_at' => NULL,
                'password' => '$2y$12$L.8jPcQCEFOxzFAda4tiU.pjdqEsrKz3Cihh/chjCHqxN5p8ny1xK',
                'remember_token' => NULL,
                'created_at' => '2026-07-07 15:03:30',
                'updated_at' => '2026-07-07 15:03:30',
            ),
            34 => 
            array (
                'id' => 59,
                'parent_id' => NULL,
                'name' => 'BKHIT Sulawesi Barat',
                'email' => 'bkhitsulawesibarat@gmail.com',
                'role' => 'bkhit',
                'upt_asal' => 'BKHIT Sulawesi Barat',
                'email_verified_at' => NULL,
                'password' => '$2y$12$L.8jPcQCEFOxzFAda4tiU.pjdqEsrKz3Cihh/chjCHqxN5p8ny1xK',
                'remember_token' => NULL,
                'created_at' => '2026-07-07 15:03:30',
                'updated_at' => '2026-07-07 15:03:30',
            ),
            35 => 
            array (
                'id' => 60,
                'parent_id' => NULL,
                'name' => 'BKHIT Sulawesi Tenggara',
                'email' => 'bkhitsulawesitenggara@gmail.com',
                'role' => 'bkhit',
                'upt_asal' => 'BKHIT Sulawesi Tenggara',
                'email_verified_at' => NULL,
                'password' => '$2y$12$L.8jPcQCEFOxzFAda4tiU.pjdqEsrKz3Cihh/chjCHqxN5p8ny1xK',
                'remember_token' => NULL,
                'created_at' => '2026-07-07 15:03:30',
                'updated_at' => '2026-07-07 15:03:30',
            ),
            36 => 
            array (
                'id' => 61,
                'parent_id' => NULL,
                'name' => 'BKHIT Maluku',
                'email' => 'bkhitmaluku@gmail.com',
                'role' => 'bkhit',
                'upt_asal' => 'BKHIT Maluku',
                'email_verified_at' => NULL,
                'password' => '$2y$12$L.8jPcQCEFOxzFAda4tiU.pjdqEsrKz3Cihh/chjCHqxN5p8ny1xK',
                'remember_token' => NULL,
                'created_at' => '2026-07-07 15:03:30',
                'updated_at' => '2026-07-07 15:03:30',
            ),
            37 => 
            array (
                'id' => 62,
                'parent_id' => NULL,
                'name' => 'BKHIT Maluku Utara',
                'email' => 'bkhitmalukuutara@gmail.com',
                'role' => 'bkhit',
                'upt_asal' => 'BKHIT Maluku Utara',
                'email_verified_at' => NULL,
                'password' => '$2y$12$L.8jPcQCEFOxzFAda4tiU.pjdqEsrKz3Cihh/chjCHqxN5p8ny1xK',
                'remember_token' => NULL,
                'created_at' => '2026-07-07 15:03:30',
                'updated_at' => '2026-07-07 15:03:30',
            ),
            38 => 
            array (
                'id' => 63,
                'parent_id' => NULL,
                'name' => 'BKHIT Papua Barat',
                'email' => 'bkhitpapuabarat@gmail.com',
                'role' => 'bkhit',
                'upt_asal' => 'BKHIT Papua Barat',
                'email_verified_at' => NULL,
                'password' => '$2y$12$L.8jPcQCEFOxzFAda4tiU.pjdqEsrKz3Cihh/chjCHqxN5p8ny1xK',
                'remember_token' => NULL,
                'created_at' => '2026-07-07 15:03:30',
                'updated_at' => '2026-07-07 15:03:30',
            ),
            39 => 
            array (
                'id' => 64,
                'parent_id' => NULL,
                'name' => 'BKHIT Papua Barat Daya',
                'email' => 'bkhitpapuabaratdaya@gmail.com',
                'role' => 'bkhit',
                'upt_asal' => 'BKHIT Papua Barat Daya',
                'email_verified_at' => NULL,
                'password' => '$2y$12$L.8jPcQCEFOxzFAda4tiU.pjdqEsrKz3Cihh/chjCHqxN5p8ny1xK',
                'remember_token' => NULL,
                'created_at' => '2026-07-07 15:03:30',
                'updated_at' => '2026-07-07 15:03:30',
            ),
            40 => 
            array (
                'id' => 65,
                'parent_id' => NULL,
                'name' => 'BKHIT Papua Tengah',
                'email' => 'bkhitpapuatengah@gmail.com',
                'role' => 'bkhit',
                'upt_asal' => 'BKHIT Papua Tengah',
                'email_verified_at' => NULL,
                'password' => '$2y$12$L.8jPcQCEFOxzFAda4tiU.pjdqEsrKz3Cihh/chjCHqxN5p8ny1xK',
                'remember_token' => NULL,
                'created_at' => '2026-07-07 15:03:30',
                'updated_at' => '2026-07-07 15:03:30',
            ),
            41 => 
            array (
                'id' => 66,
                'parent_id' => NULL,
                'name' => 'BKHIT Papua Selatan',
                'email' => 'bkhitpapuaselatan@gmail.com',
                'role' => 'bkhit',
                'upt_asal' => 'BKHIT Papua Selatan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$L.8jPcQCEFOxzFAda4tiU.pjdqEsrKz3Cihh/chjCHqxN5p8ny1xK',
                'remember_token' => NULL,
                'created_at' => '2026-07-07 15:03:30',
                'updated_at' => '2026-07-07 15:03:30',
            ),
            42 => 
            array (
                'id' => 67,
                'parent_id' => NULL,
                'name' => 'BKHIT Papua Pegunungan',
                'email' => 'bkhitpapuapegunungan@gmail.com',
                'role' => 'bkhit',
                'upt_asal' => 'BKHIT Papua Pegunungan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$Qqrs48gNlorPxO2lbD0w2OtmSjOAqr3E0Qd5QEQ.xGMlTIdMjUC6C',
                'remember_token' => NULL,
                'created_at' => '2026-07-08 13:51:28',
                'updated_at' => '2026-07-08 13:51:28',
            ),
        ));
        
        
    }
}